### ISSUE TITLE
missing \\ in path

### ISSUE THREAD

**Issue by Fuzzy2319** [Anosema/ShapeGenerator#1]
![image](https://user-images.githubusercontent.com/61144247/103150319-3a4f0380-4773-11eb-825f-981edbe9c866.png)
in order to fix this add \\\ in this line 
![image](https://user-images.githubusercontent.com/61144247/103150341-85691680-4773-11eb-8233-5e7818bbedde.png)

**Comment by Anosema** [comment]
Fixed
